name: om
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  universal_platform: ^1.0.0+1
  dio: ^5.0.0
<<<<<<< HEAD
=======
  intl: ^0.18.1
>>>>>>> 49698c5286fc4adadd4cb6a4d37e293808b90be5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
