import 'package:get/get.dart';
import 'package:om/Api%20Service/Admin/route_service.dart';
import 'package:om/Model/Admin/route_model.dart';

class RouteController extends GetxController {
  final RouteService _routeService = RouteService();
  var routeName = ''.obs;
  var isActive = false.obs;

  void setRouteName(String name) {
    routeName.value = name;
  }

  void toggleIsActive(bool value) {
    isActive.value = value;
  }

  Future<void> saveRoute() async {
    if (routeName.isNotEmpty) {
      final newRoute = RouteModel(
        id: 1, // Assuming you can set this later or it will be generated by the backend
        route: routeName.value,
        isActive: isActive.value,
        createdBy: 1,
        updatedBy: 1,
      );

      try {
        await _routeService.saveRoute(newRoute);
        Get.snackbar('Success', 'Route saved successfully');
      } catch (e) {
        Get.snackbar('Error', 'Failed to save route: $e');
      }
    } else {
      Get.snackbar('Error', 'Please enter a route name');
    }
  }
}
